# Generated by Django 4.2.30 on 2026-09-16 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('payment_terms', models.CharField(blank=True, max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_point_of_contact', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.client')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bill_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_structure_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(max_length=50, unique=True)),
                ('job_name', models.CharField(max_length=255)),
                ('work_type', models.CharField(choices=[('New Construction', 'New Construction'), ('Renovation', 'Renovation'), ('Addition', 'Addition'), ('Assessment', 'Assessment')], max_length=30)),
                ('complexity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('job_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=10)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('size_unit', models.CharField(blank=True, max_length=30)),
                ('construction_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Hold', 'On Hold'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('start_date', models.DateField()),
                ('est_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.client')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.contact')),
                ('delivery_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.deliverymethod')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OwnerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtypes', to='core.projecttype')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StructuralSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_date', models.DateField()),
                ('project_name', models.CharField(max_length=255)),
                ('est_construction_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('proposed_fee', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Won', 'Won'), ('Lost', 'Lost'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('loss_reason', models.CharField(blank=True, max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='core.client')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='core.owner')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='core.projecttype')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='owner_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owners', to='core.ownertype'),
        ),
        migrations.CreateModel(
            name='JobStructuralSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.job')),
                ('structural_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.structuralsystem')),
            ],
        ),
        migrations.CreateModel(
            name='JobPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_name', models.CharField(max_length=100)),
                ('budget_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('budget_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('percent_complete', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('is_change_order', models.BooleanField(default=False)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_fees', to='core.feestructure')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.job')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_fees', to='core.servicetype')),
            ],
        ),
        migrations.CreateModel(
            name='JobCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('Labor', 'Labor'), ('Subconsultant', 'Subconsultant'), ('Reimbursable Expense', 'Reimbursable Expense')], max_length=30)),
                ('cost_date', models.DateField()),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='core.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='core.job')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='core.jobphase')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.owner'),
        ),
        migrations.AddField(
            model_name='job',
            name='pm_employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.employee'),
        ),
        migrations.AddField(
            model_name='job',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.projecttype'),
        ),
        migrations.AddField(
            model_name='job',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.proposal'),
        ),
        migrations.AddField(
            model_name='job',
            name='structural_systems',
            field=models.ManyToManyField(related_name='jobs', through='core.JobStructuralSystem', to='core.structuralsystem'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Paid', 'Paid'), ('Void', 'Void')], default='Draft', max_length=20)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='BacklogSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('billed_to_date', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remaining_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('projected_completion', models.DateField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backlog_snapshots', to='core.job')),
            ],
        ),
        migrations.AddConstraint(
            model_name='jobstructuralsystem',
            constraint=models.UniqueConstraint(fields=('job', 'structural_system'), name='unique_job_structural_system'),
        ),
    ]
